### ISSUE TITLE
demo运行报数据库错误

### ISSUE THREAD

**Issue by dustturtle** [dota1989/myspringboot#1]
请问从github上下载的程序在idea运行，登陆时报数据库错误，需要执行什么操作吗？

**Comment by dustturtle** [comment]
mysql已经安装

**Comment by mczb1989** [comment]
报什么错，贴出来

**Comment by dustturtle** [comment]
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'zb_db.role' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_211]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_211]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]

**Comment by dustturtle** [comment]
这是我最新的报错，我自己创建了一个zb_db的mysql表（根据你教程中的语句），但我现在看报错感觉像是数据库不匹配？ 能否发一份对应的数据库？ 非常感谢 openglnewbee@163.com

**Comment by dustturtle** [comment]
参考的教程：https://www.cnblogs.com/zhangbin1989/p/9473292.html

**Comment by mczb1989** [comment]
Table 'zb_db.role' doesn't exist
提示表不存在
你把sql执行下：/src/main/resources/sql
https://github.com/mczb1989/myspringboot/tree/master/src/main/resources/sql
